name: test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install modules
      run: npm install
    - name: Run build
      run: npm run publish
    - name: Run tests
      run: npm test
